//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TarefaTeste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarefas
    {
        public int ID { get; set; }
        public string Descricao { get; set; }
        public System.DateTime Data { get; set; }
        public int IDUsuario { get; set; }
        public int IDStatusTarefa { get; set; }
    
        public virtual StatusTarefa StatusTarefa { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
